version: "3"

services:
  cassandra-1:
    container_name: cassandra-1
    networks: ["dc_test_net"]
    hostname: cassandra-node-1
    image: cassandra:latest
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_SEEDS=cassandra-1.vnet
      - CASSANDRA_LISTEN_ADDRESS=cassandra-1.vnet
      - MAX_HEAP_SIZE=1024M
      - HEAP_NEWSIZE=200M

  cassandra-2:
    container_name: cassandra-2
    networks: ["dc_test_net"]
    hostname: cassandra-node-2
    image: cassandra:latest
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_SEEDS=cassandra-1.vnet
      - MAX_HEAP_SIZE=1024M
      - HEAP_NEWSIZE=200M

  cassandra-3:
    container_name: cassandra-3
    networks: ["dc_test_net"]
    hostname: cassandra-node-3
    image: cassandra:latest
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_SEEDS=cassandra-1.vnet
      - MAX_HEAP_SIZE=1024M
      - HEAP_NEWSIZE=200M 

networks:
  vnet:
    external:
      name: dc_test_net
